version: '3'

services:
  # Datenbank Server
  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpnetwork
  

# Speicher Volume
volumes:
  db_data:
    driver: local

#Netzwerk
networks:
  wpnetwork:
    driver: bridge
