version: '3'

services:
  # ------------------ Wordpress Service ------------------------
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress
    restart: always
    # Definiert das Envoirement
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    # Definiert die Reccourcen und Limite
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
        reservations:
          cpus: '0.5'
          memory: 200M
    # Definiert das Volume
    volumes:
        - wp_data:/var/www/html
    # Definiert die Ports
    ports:
      - '8000:80'
    # Definiert das Netzwerk
    networks:
      - wpnetwork
  # ----------------- Datenbank Server ---------------------------
  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    # Definiert das Envoirement
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    # Definiert die Reccourcen und Limite
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 200M
    # Definiert das Volume
    volumes:
      - db_data:/var/lib/mysql
    # Definiert die Ports
    ports:
      - '3306:3306'
    # Definiert das Netzwerk
    networks:
      - wpnetwork
    # ---------------- phpmyadmin service ------------------------
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    # Definiert das Envoirement
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: wordpress
    # Definiert die Reccourcen und Limite
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
        reservations:
          cpus: '0.5'
          memory: 200M
    # Definiert die Ports
    ports:
      - '8080:80'
    # Definiert das Netzwerk
    networks:
      - wpnetwork
# Speicher Volume
volumes:
  db_data:
    driver: local
  wp_data:
    driver: local
# Netzwerk
networks:
  wpnetwork:
    driver: bridge