version: '3'

services:
### MySQL Container
  mysql:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=mywordpressdb
      - MYSQL_USER=mywordpressuser
      - MYSQL_PASSWORD=mywordpresspassword
      - MYSQL_ROOT_PASSWORD=myrootpassword
    networks:
      - my-network

volumes:
  mysql_data:
    driver: local

networks:
  my-network:
    driver: bridge
